### ISSUE TITLE
Jr./Sr. handling

### ISSUE THREAD

**Issue by metasj** [catleeball/tmnt_wikipedia_bot#7]
Four-word names ending in "Jr." or "Sr." should include the last two words (lastname, Jr.) in the subtitle.

**Comment by catleeball** [comment]
It could be interesting to lump whole names and titles together within the logo, including suffixes (jr, sr, ordinal titles) as well as prefixes (dr, mx) or even titles (duke, king, queen).

That said, it might be a little while before I make more progress on this project since I'm pretty busy with life stuff currently (about to move to another state and change to a new position at work).

Feel free to submit PRs in the meantime though if you wish. :slightly_smiling_face:

**Comment by catleeball** [comment]
I might close this, I don't mind the sometimes whimsical clustering of words, and the language processing involved might be a little more messy than it's worth. Thank you for the suggestion though!
